FROM openjdk:8-jdk-alpine
LABEL maintainer="nils.kuhn@iteratec.com"

USER root:root

ARG LOGSTASH_VERSION=7.3.0
ARG PATH_LOGSTASH_HOME=/opt/logstash
WORKDIR /opt/logstash

RUN apk update && \
    apk add git && \
    apk add ruby-rake && \
    rm -rf /var/cache/apk/*

RUN git clone https://github.com/elastic/logstash.git $PATH_LOGSTASH_HOME && \
    git checkout v$LOGSTASH_VERSION && \
    ./gradlew bootstrap && \
    ./bin/logstash-plugin install --development && \
    rake test:install-default

VOLUME ["$PATH_LOGSTASH_HOME/filters-under-test", "$PATH_LOGSTASH_HOME/rspec-tests"]

ENTRYPOINT ["/opt/logstash/bin/rspec", "-P", "/opt/logstash/rspec-tests/**/*_spec.rb"]